function [BER_full, BER_oneTap, SNR_dB, results] = RX_author_style(folderName)
%RX_AUTHOR_STYLE  ODSS receiver using the author's channel-matched dictionary.
%
% This receiver keeps the user's existing transmitter unchanged:
%
%   X = T_iMF*x
%   s = G_tx*X
%
% At the receiver, every column of G_tx is passed through the same
% delay-scale channel to form
%
%   Grx_author = H_time*G_tx.
%
% The received waveform is therefore
%
%   r = Grx_author*T_iMF*x + w.
%
% Two receivers are evaluated:
%
%   1) Full waveform-domain LMMSE
%      x_hat = (A^H*A + sigma_w^2/E_s I)^(-1) A^H*r,
%      where A = Grx_author*T_iMF.
%
%   2) Author-style one-tap approximation
%      Y  = Ts*Grx_author^H*r,
%      Hd = Ts*Grx_author^H*Grx_author,
%      X_hat = (diag(diag(Hd)) + Ts*sigma_w^2/E_X I)^(-1)Y,
%      x_hat = T_iMF\X_hat.
%
% INPUT
%   folderName : folder containing TX_Data.mat generated by the current TX.
%
% OUTPUTS
%   BER_full   : BER of full waveform-domain LMMSE.
%   BER_oneTap : BER of author-style diagonal/one-tap receiver.
%   SNR_dB     : requested received waveform SNR values.
%   results    : structure containing BER/SER, diagnostics and final frame.
%
% Required variables in TX_Data.mat:
%   tx_bits, x_data, X_data, num_run, num_blocks,
%   QAM_order, bitsPerSymbol, q, Nscale, B, W, T, Fs, Ts,
%   M_tot, T_iMF, Ns, t, G_tx.
%
% MATLAB R2018b or newer is recommended.

    %% ================================================================
    % 1. User settings
    % ================================================================

    % Received waveform SNR. This follows the author's waveform-level
    % convention, not the previous recovered-source-domain SNR convention.
    SNR_dB = -9:3:21;

    % Delay-scale channel settings.
    Path_num = 20;
    tau_max = 10e-3;
    alpha_max = 1.002;

    % true  : normalize sum_p |h_p|^2 to one, matching the user's recent code.
    % false : leave E|h_p|^2=1 per path, closer to the uploaded author code.
    normalizePathEnergy = true;

    % One random channel realization per run; all blocks in the same run use
    % the same channel. This avoids rebuilding the large dictionary per SNR.
    randomSeed = 20260731;

    % Interpolation used by both the actual waveform channel and dictionary.
    interpolationMethod = 'linear';

    % Progress display cadence.
    displayEveryRuns = 10;

    rng(randomSeed);

    %% ================================================================
    % 2. Load TX data
    % ================================================================

    dataFile = fullfile(folderName, 'TX_Data.mat');

    if exist(dataFile, 'file') ~= 2
        error('RX_author_style:MissingTXData', ...
            'Cannot find TX_Data.mat in folder: %s', folderName);
    end

    S = load(dataFile);

    requiredNames = { ...
        'tx_bits', 'x_data', 'X_data', ...
        'num_run', 'num_blocks', ...
        'QAM_order', 'bitsPerSymbol', ...
        'q', 'Nscale', 'B', 'W', 'T', 'Fs', 'Ts', ...
        'M_tot', 'T_iMF', 'Ns', 't', 'G_tx'};

    for kk = 1:numel(requiredNames)
        if ~isfield(S, requiredNames{kk})
            error('RX_author_style:MissingVariable', ...
                'TX_Data.mat does not contain required variable "%s".', ...
                requiredNames{kk});
        end
    end

    tx_bits       = S.tx_bits;
    x_data        = S.x_data;
    X_data        = S.X_data;
    num_run       = S.num_run;
    num_blocks    = S.num_blocks;
    QAM_order     = S.QAM_order;
    bitsPerSymbol = S.bitsPerSymbol;
    q             = S.q;
    Nscale        = S.Nscale;
    B             = S.B;
    W             = S.W;
    T             = S.T;
    Fs            = S.Fs;
    Ts            = S.Ts;
    M_tot         = S.M_tot;
    T_iMF         = S.T_iMF;
    Ns            = S.Ns;
    t             = S.t(:);
    G_tx          = S.G_tx;

    if size(G_tx,1) ~= numel(t)
        error('RX_author_style:TimeDimensionMismatch', ...
            'size(G_tx,1) must equal length(t).');
    end

    if size(G_tx,2) ~= M_tot
        error('RX_author_style:DictionaryDimensionMismatch', ...
            'size(G_tx,2) must equal M_tot.');
    end

    if any(size(T_iMF) ~= [M_tot M_tot])
        error('RX_author_style:TransformDimensionMismatch', ...
            'T_iMF must be M_tot-by-M_tot.');
    end

    if abs(Ts - 1/Fs) > 100*eps(max(abs([Ts,1/Fs])))
        warning('RX_author_style:TsMismatch', ...
            'Saved Ts is not numerically equal to 1/Fs. Saved Ts is used.');
    end

    numSNR = numel(SNR_dB);
    numFrames = num_run*num_blocks;

    fprintf('============================================================\n');
    fprintf('Author-style ODSS channel-matched receiver\n');
    fprintf('q = %.3f, Nscale = %d, M_tot = %d\n', q, Nscale, M_tot);
    fprintf('B = %.3f Hz, W = %.6f Hz, T = %.6f s\n', B, W, T);
    fprintf('Fs = %.1f Hz, Ns = %d\n', Fs, Ns);
    fprintf('runs = %d, blocks/run = %d, frames = %d\n', ...
        num_run, num_blocks, numFrames);
    fprintf('channel: paths = %d, tau_max = %.3f ms, alpha_max = %.7f\n', ...
        Path_num, 1e3*tau_max, alpha_max);
    fprintf('path-energy normalization = %d\n', normalizePathEnergy);
    fprintf('============================================================\n\n');

    %% ================================================================
    % 3. Accumulators
    % ================================================================

    bitErrorsFull = zeros(1,numSNR);
    bitErrorsOne  = zeros(1,numSNR);
    symbolErrorsFull = zeros(1,numSNR);
    symbolErrorsOne  = zeros(1,numSNR);

    totalBits = zeros(1,numSNR);
    totalSymbols = zeros(1,numSNR);

    measuredWaveformSNR = zeros(1,numSNR);
    measuredDecisionSNRFull = zeros(1,numSNR);
    measuredDecisionSNROne = zeros(1,numSNR);
    measurementCount = zeros(1,numSNR);

    dictionaryErrorSum = 0;
    dictionaryErrorMax = 0;
    offDiagonalRatioSum = 0;
    offDiagonalRatioMax = 0;
    channelConditionSum = 0;

    finalFrame = struct();

    %% ================================================================
    % 4. Loop over random channel realizations
    % ================================================================

    for runIndex = 1:num_run

        %% 4.1 Generate one delay-scale channel for this run
        tau_p = [0; tau_max*rand(max(Path_num-1,0),1)];
        tau_p = sort(tau_p, 'ascend');

        alpha_p = 1/alpha_max + ...
            (alpha_max - 1/alpha_max)*rand(Path_num,1);

        h_p = (randn(Path_num,1) + 1j*randn(Path_num,1))/sqrt(2);

        if normalizePathEnergy
            hNorm = norm(h_p);
            if hNorm <= eps
                error('RX_author_style:ZeroChannel', ...
                    'Generated path-gain vector has zero norm.');
            end
            h_p = h_p/hNorm;
        end

        %% 4.2 Receiver observation interval
        % Each warped basis can last approximately T/alpha_p after tau_p.
        tEnd = max([T; tau_p + T./alpha_p]);
        Nrx = ceil(tEnd*Fs) + 1;
        t_rx = (0:Nrx-1).'/Fs;

        %% 4.3 Author's Grx: channel-affected transmit dictionary
        % Grx_author(:,j) is the received waveform produced by G_tx(:,j).
        Grx_author = applyChannelToDictionary( ...
            G_tx, t, t_rx, h_p, tau_p, alpha_p, interpolationMethod);

        % Complete waveform-domain matrix from source QAM symbols to r(t).
        A_full = Grx_author*T_iMF;

        % Author-style channel-matched Gram matrix.
        Hd = Ts*(Grx_author'*Grx_author);
        Hd = (Hd + Hd')/2;

        HdDiagonal = diag(diag(Hd));
        offDiagonalRatio = norm(Hd-HdDiagonal,'fro') / ...
            max(norm(Hd,'fro'),eps);

        channelCondition = cond(A_full'*A_full);

        offDiagonalRatioSum = offDiagonalRatioSum + offDiagonalRatio;
        offDiagonalRatioMax = max(offDiagonalRatioMax,offDiagonalRatio);
        channelConditionSum = channelConditionSum + channelCondition;

        %% 4.4 Loop over blocks using this channel
        for blockIndex = 1:num_blocks

            x_true = x_data(:,blockIndex,runIndex);
            X_true = X_data(:,blockIndex,runIndex);
            bits_true = double(tx_bits(:,blockIndex,runIndex));

            x_true = x_true(:);
            X_true = X_true(:);
            bits_true = bits_true(:);

            if numel(x_true) ~= M_tot || numel(X_true) ~= M_tot
                error('RX_author_style:FrameDimensionMismatch', ...
                    'x_data and X_data must contain M_tot entries per frame.');
            end

            if numel(bits_true) ~= M_tot*bitsPerSymbol
                error('RX_author_style:BitDimensionMismatch', ...
                    'Each tx_bits frame must contain M_tot*bitsPerSymbol bits.');
            end

            % Reconstruct the transmitted waveform from the saved TX matrices.
            s_tx = G_tx*X_true;

            % Apply the same physical channel directly to s_tx.
            r_s_direct = applyChannelToWaveform( ...
                s_tx, t, t_rx, h_p, tau_p, alpha_p, interpolationMethod);

            % Matrix/dictionary representation of the same channel output.
            r_s = Grx_author*X_true;

            dictionaryError = norm(r_s-r_s_direct) / ...
                max(norm(r_s_direct),eps);

            dictionaryErrorSum = dictionaryErrorSum + dictionaryError;
            dictionaryErrorMax = max(dictionaryErrorMax,dictionaryError);

            Es_source = real(mean(abs(x_true).^2));
            Es_X = real(mean(abs(X_true).^2));

            if Es_source <= 0 || Es_X <= 0
                error('RX_author_style:NonpositiveSymbolEnergy', ...
                    'Source/transform-domain symbol energy must be positive.');
            end

            trueSymbolIndices = qamdemod( ...
                x_true, QAM_order, 'gray', 'UnitAveragePower', true);
            trueSymbolIndices = double(trueSymbolIndices(:));

            %% 4.5 Loop over waveform SNR
            signalPower = mean(abs(r_s).^2);

            for ss = 1:numSNR
                SNR_linear = 10^(SNR_dB(ss)/10);
                noisePower = signalPower/SNR_linear;

                w_time = sqrt(noisePower/2) .* ...
                    (randn(Nrx,1) + 1j*randn(Nrx,1));

                r = r_s + w_time;

                % --------------------------------------------------------
                % Full waveform-domain LMMSE
                % --------------------------------------------------------
                lambdaFull = noisePower/Es_source;

                normalMatrix = A_full'*A_full + ...
                    lambdaFull*eye(M_tot);

                x_hat_full = normalMatrix \ (A_full'*r);

                % Signal/noise components through the same linear receiver.
                x_signal_full = normalMatrix \ (A_full'*r_s);
                x_noise_full  = normalMatrix \ (A_full'*w_time);

                % --------------------------------------------------------
                % Author-style channel-matched one-tap receiver
                % --------------------------------------------------------
                Y_author = Ts*(Grx_author'*r);
                Y_signal_author = Ts*(Grx_author'*r_s);
                Y_noise_author = Ts*(Grx_author'*w_time);

                % Multiplying the author's unscaled normal equations by Ts
                % makes the regularization term Ts*noisePower/Es_X.
                lambdaOne = Ts*noisePower/Es_X;
                oneTapMatrix = HdDiagonal + lambdaOne*eye(M_tot);

                X_hat_one = oneTapMatrix \ Y_author;
                X_signal_one = oneTapMatrix \ Y_signal_author;
                X_noise_one = oneTapMatrix \ Y_noise_author;

                % T_iMF is not unitary, so use a solve, not T_iMF'.
                x_hat_one = T_iMF \ X_hat_one;
                x_signal_one = T_iMF \ X_signal_one;
                x_noise_one = T_iMF \ X_noise_one;

                % --------------------------------------------------------
                % QAM decisions
                % --------------------------------------------------------
                bits_hat_full = qamdemod( ...
                    x_hat_full, QAM_order, 'gray', ...
                    'OutputType', 'bit', 'UnitAveragePower', true);
                bits_hat_full = double(bits_hat_full(:));

                bits_hat_one = qamdemod( ...
                    x_hat_one, QAM_order, 'gray', ...
                    'OutputType', 'bit', 'UnitAveragePower', true);
                bits_hat_one = double(bits_hat_one(:));

                symbolIndicesFull = qamdemod( ...
                    x_hat_full, QAM_order, 'gray', ...
                    'UnitAveragePower', true);
                symbolIndicesFull = double(symbolIndicesFull(:));

                symbolIndicesOne = qamdemod( ...
                    x_hat_one, QAM_order, 'gray', ...
                    'UnitAveragePower', true);
                symbolIndicesOne = double(symbolIndicesOne(:));

                bitErrorsFull(ss) = bitErrorsFull(ss) + ...
                    nnz(bits_hat_full ~= bits_true);
                bitErrorsOne(ss) = bitErrorsOne(ss) + ...
                    nnz(bits_hat_one ~= bits_true);

                symbolErrorsFull(ss) = symbolErrorsFull(ss) + ...
                    nnz(symbolIndicesFull ~= trueSymbolIndices);
                symbolErrorsOne(ss) = symbolErrorsOne(ss) + ...
                    nnz(symbolIndicesOne ~= trueSymbolIndices);

                totalBits(ss) = totalBits(ss) + numel(bits_true);
                totalSymbols(ss) = totalSymbols(ss) + M_tot;

                measuredWaveformSNR(ss) = measuredWaveformSNR(ss) + ...
                    10*log10(mean(abs(r_s).^2)/max(mean(abs(w_time).^2),eps));

                measuredDecisionSNRFull(ss) = measuredDecisionSNRFull(ss) + ...
                    10*log10(mean(abs(x_signal_full).^2) / ...
                    max(mean(abs(x_noise_full).^2),eps));

                measuredDecisionSNROne(ss) = measuredDecisionSNROne(ss) + ...
                    10*log10(mean(abs(x_signal_one).^2) / ...
                    max(mean(abs(x_noise_one).^2),eps));

                measurementCount(ss) = measurementCount(ss) + 1;

                if runIndex == num_run && ...
                        blockIndex == num_blocks && ss == numSNR
                    finalFrame.runIndex = runIndex;
                    finalFrame.blockIndex = blockIndex;
                    finalFrame.SNR_dB = SNR_dB(ss);
                    finalFrame.t_rx = t_rx;
                    finalFrame.tau_p = tau_p;
                    finalFrame.alpha_p = alpha_p;
                    finalFrame.h_p = h_p;
                    finalFrame.s_tx = s_tx;
                    finalFrame.r_s = r_s;
                    finalFrame.w_time = w_time;
                    finalFrame.r = r;
                    finalFrame.Hd = Hd;
                    finalFrame.A_full = A_full;
                    finalFrame.x_true = x_true;
                    finalFrame.X_true = X_true;
                    finalFrame.x_hat_full = x_hat_full;
                    finalFrame.x_hat_oneTap = x_hat_one;
                    finalFrame.X_hat_oneTap = X_hat_one;
                    finalFrame.bits_true = bits_true;
                    finalFrame.bits_hat_full = bits_hat_full;
                    finalFrame.bits_hat_oneTap = bits_hat_one;
                    finalFrame.dictionaryError = dictionaryError;
                    finalFrame.offDiagonalRatio = offDiagonalRatio;
                end
            end
        end

        if mod(runIndex,displayEveryRuns) == 0 || ...
                runIndex == 1 || runIndex == num_run
            fprintf(['Completed run %d/%d: dictionary error %.3e, ', ...
                'off-diagonal ratio %.3e, cond(A^H A) %.3e\n'], ...
                runIndex, num_run, dictionaryError, ...
                offDiagonalRatio, channelCondition);
        end
    end

    %% ================================================================
    % 5. Final results
    % ================================================================

    BER_full = bitErrorsFull ./ max(totalBits,1);
    BER_oneTap = bitErrorsOne ./ max(totalBits,1);

    SER_full = symbolErrorsFull ./ max(totalSymbols,1);
    SER_oneTap = symbolErrorsOne ./ max(totalSymbols,1);

    measuredWaveformSNR = measuredWaveformSNR ./ max(measurementCount,1);
    measuredDecisionSNRFull = measuredDecisionSNRFull ./ max(measurementCount,1);
    measuredDecisionSNROne = measuredDecisionSNROne ./ max(measurementCount,1);

    meanDictionaryError = dictionaryErrorSum/max(numFrames,1);
    meanOffDiagonalRatio = offDiagonalRatioSum/max(num_run,1);
    meanChannelCondition = channelConditionSum/max(num_run,1);

    fprintf('\n================ Final BER results ================\n');
    for ss = 1:numSNR
        fprintf(['SNR = %6.1f dB | measured wav = %6.2f dB | ', ...
            'full BER = %.6e | one-tap BER = %.6e\n'], ...
            SNR_dB(ss), measuredWaveformSNR(ss), ...
            BER_full(ss), BER_oneTap(ss));
    end

    fprintf('\nDiagnostics averaged over the simulation\n');
    fprintf('mean dictionary error       = %.3e\n', meanDictionaryError);
    fprintf('maximum dictionary error    = %.3e\n', dictionaryErrorMax);
    fprintf('mean off-diagonal ratio     = %.3e\n', meanOffDiagonalRatio);
    fprintf('maximum off-diagonal ratio  = %.3e\n', offDiagonalRatioMax);
    fprintf('mean cond(A^H A)            = %.3e\n', meanChannelCondition);

    %% ================================================================
    % 6. Plots
    % ================================================================

    figure;
    semilogy(SNR_dB, BER_full, '-o', 'LineWidth', 1.5);
    hold on;
    semilogy(SNR_dB, BER_oneTap, '-s', 'LineWidth', 1.5);
    grid on;
    ylim([1e-6 1]);
    xlabel('Received waveform SNR (dB)');
    ylabel('Bit Error Rate');
    title(sprintf( ...
        'Author-style ODSS receiver, q = %.2f, N_{scale} = %d', ...
        q, Nscale));
    legend('Full waveform LMMSE', 'One-tap diagonal', ...
        'Location', 'southwest');

    figure;
    plot(real(finalFrame.x_hat_full), imag(finalFrame.x_hat_full), 'o');
    hold on;
    plot(real(finalFrame.x_hat_oneTap), ...
        imag(finalFrame.x_hat_oneTap), 's');
    plot(real(finalFrame.x_true), imag(finalFrame.x_true), ...
        'kx', 'LineWidth', 1.5);
    grid on;
    axis equal;
    xlabel('In-phase');
    ylabel('Quadrature');
    title(sprintf('Final constellation, waveform SNR = %.1f dB', ...
        finalFrame.SNR_dB));
    legend('Full waveform LMMSE', 'One-tap diagonal', ...
        'Transmitted', 'Location', 'best');

    figure;
    imagesc(20*log10( ...
        abs(finalFrame.Hd)/max(abs(finalFrame.Hd(:))) + 1e-12));
    axis image;
    colorbar;
    caxis([-60 0]);
    xlabel('Transmit dictionary index');
    ylabel('Matched-filter index');
    title('Author-style H_d = T_s G_{ch}^H G_{ch} (dB)');

    %% ================================================================
    % 7. Save results
    % ================================================================

    results = struct();
    results.receiver = 'author-style channel-matched dictionary';
    results.SNR_dB = SNR_dB;
    results.BER_full = BER_full;
    results.BER_oneTap = BER_oneTap;
    results.SER_full = SER_full;
    results.SER_oneTap = SER_oneTap;
    results.measuredWaveformSNR = measuredWaveformSNR;
    results.measuredDecisionSNRFull = measuredDecisionSNRFull;
    results.measuredDecisionSNROne = measuredDecisionSNROne;
    results.Path_num = Path_num;
    results.tau_max = tau_max;
    results.alpha_max = alpha_max;
    results.normalizePathEnergy = normalizePathEnergy;
    results.meanDictionaryError = meanDictionaryError;
    results.maximumDictionaryError = dictionaryErrorMax;
    results.meanOffDiagonalRatio = meanOffDiagonalRatio;
    results.maximumOffDiagonalRatio = offDiagonalRatioMax;
    results.meanChannelCondition = meanChannelCondition;
    results.finalFrame = finalFrame;

    rxDataFile = fullfile(folderName, ...
        sprintf('RX_AUTHOR_STYLE_q%g_Nscale%d.mat', q, Nscale));
    save(rxDataFile, 'results', 'BER_full', 'BER_oneTap', 'SNR_dB', '-v7.3');

    fprintf('\nReceiver results saved to:\n%s\n', rxDataFile);
end


function G_out = applyChannelToDictionary( ...
    G_in, t_tx, t_rx, h_p, tau_p, alpha_p, interpolationMethod)
%APPLYCHANNELTODICTIONARY Apply one delay-scale channel to all columns.

    numPaths = numel(h_p);
    G_out = complex(zeros(numel(t_rx),size(G_in,2)));

    for p = 1:numPaths
        queryTime = alpha_p(p)*(t_rx-tau_p(p));

        G_path = interp1( ...
            t_tx, G_in, queryTime, interpolationMethod, 0);

        G_out = G_out + ...
            h_p(p)*sqrt(alpha_p(p))*G_path;
    end
end


function y_out = applyChannelToWaveform( ...
    y_in, t_tx, t_rx, h_p, tau_p, alpha_p, interpolationMethod)
%APPLYCHANNELTOWAVEFORM Apply the same delay-scale channel to one waveform.

    numPaths = numel(h_p);
    y_out = complex(zeros(numel(t_rx),1));
    y_in = y_in(:);

    for p = 1:numPaths
        queryTime = alpha_p(p)*(t_rx-tau_p(p));

        y_path = interp1( ...
            t_tx, y_in, queryTime, interpolationMethod, 0);

        y_out = y_out + ...
            h_p(p)*sqrt(alpha_p(p))*y_path;
    end
end
