%% ODSS receiver
% Read the waveform generated by TX.m, pass it through the configured
% constant-gain AWGN channel, decode it, and save the decoded data.
%
% Input:
%   TX_data.mat
%
% Output:
%   RX_decoded_data.mat
%   BER_SNR_data.mat
%   BER_SNR_curve.png
%
% MATLAB R2016b or newer is required for local functions in scripts.

clear; clc; close all;

%% 1. Receiver/channel settings
h0 = 1; % Example: 0.8*exp(1j*pi/5)
numCurveFrames = 100;

rxScriptDir = fileparts(mfilename('fullpath'));
txDataFile = fullfile(rxScriptDir, 'TX_data.mat');
rxDataFile = fullfile(rxScriptDir, 'RX_decoded_data.mat');

if exist(txDataFile, 'file') ~= 2
    error(['Cannot find %s. Run TX.m first to generate the ', ...
        'transmitter data.'], txDataFile);
end

%% 2. Load and validate transmitter data
tx = load(txDataFile);

requiredFields = { ...
    'txFormatVersion', 'q', 'Nscale', 'B', 'W', 'T', 'Fs', 'Ts', 'SNRdB_curve', ...
    'pulseType', 'QAM_order', 'bitsPerSymbol', ...
    'M_scale', 'M_tot', 'Ns', 't', ...
    'pair_n', 'pair_m', 'T_iMF', ...
    'tx_bits', 'x_vector', 'X_vector', 'G_tx', 'G_rx', 's_tx'};

for fieldIdx = 1:numel(requiredFields)
    if ~isfield(tx, requiredFields{fieldIdx})
        error('TX_data.mat is missing required field "%s".', ...
            requiredFields{fieldIdx});
    end
end

if tx.txFormatVersion ~= 1
    error('Unsupported TX_data.mat format version: %g.', ...
        tx.txFormatVersion);
end

q = tx.q;
Nscale = tx.Nscale;
B = tx.B;
W = tx.W;
T = tx.T;
Fs = tx.Fs;
Ts = tx.Ts;
SNRdB_curve = tx.SNRdB_curve;
pulseType = tx.pulseType;
QAM_order = tx.QAM_order;
bitsPerSymbol = tx.bitsPerSymbol;
M_scale = tx.M_scale;
M_tot = tx.M_tot;
Ns = tx.Ns;
t = tx.t;
pair_n = tx.pair_n;
pair_m = tx.pair_m;
T_iMF = tx.T_iMF;
tx_bits = tx.tx_bits;
x_vector = tx.x_vector;
X_vector = tx.X_vector;
G_tx = tx.G_tx;
G_rx = tx.G_rx;
s_tx = tx.s_tx;

if numel(s_tx) ~= Ns || numel(t) ~= Ns
    error('Saved waveform, time vector, and Ns are inconsistent.');
end

%% loop for the SNRdB
for ss = 1:length(SNRdB_curve)
    SNRdB = SNRdB_curve(ss);
    
    
    %% 11. Ideal no-delay, no-scale-spread channel plus AWGN
    %
    % h(tau,alpha) = h0*delta(tau)*delta(alpha-1)
    %
    % r(t) = h0*s(t) + w(t)
    
    h0 = 1;%0.8 * exp(1j*pi/5);   % Example constant complex channel gain
    
    s_channel = h0 * s_tx;
    
    % Define SNR using received signal power after channel gain
    signalPower = mean(abs(s_channel).^2);
    noisePower = signalPower / 10^(SNRdB/10);
    
    w_time = sqrt(noisePower/2) .* (randn(Ns,1) + 1j*randn(Ns,1));
    
    r = s_channel + w_time;
    
    measuredSNRdB = 10*log10(mean(abs(s_channel).^2) / mean(abs(w_time).^2));
    
    
    %% 12. ODSS demodulator using matched-filter function, Eq. (45)
    % Each column G_rx(:,idx) is one delay-scale receive template.
    %
    % Yhat[n,m] = integral conj(g_rx,nm(t)) * r(t) dt
    Yhat_vector = complex(zeros(M_tot,1));
    W_vector = complex(zeros(M_tot,1));
    
    for idx = 1:M_tot
    
        n = pair_n(idx);
        m = pair_m(idx);
    
        alpha_nm = q^n;
        tau_nm = m/(alpha_nm*W);
    
        % The canonical-dual receive template for this (n,m)
        template_nm = G_rx(:,idx);
    
        % Matched-filter output for the received signal
        Yhat_vector(idx) = matchedFilterSample(r, t, template_nm);
    
        % Matched-filter output for the time-domain noise
        W_vector(idx) = matchedFilterSample(w_time, t, template_nm);
    
    end
    
    %% 13. Construct the Eq. (65) diagonal channel
    h_path = h0;
    tau_path = 0;
    alpha_path = 1;
    
    h_path = h_path(:);
    tau_path = tau_path(:);
    alpha_path = alpha_path(:);
    Path_num = numel(h_path);
    
    if numel(tau_path) ~= Path_num || numel(alpha_path) ~= Path_num
        error(['h_path, tau_path, and alpha_path must have ', ...
            'the same length.']);
    end
    
    if any(alpha_path <= 0)
        error('All alpha_path values must be positive.');
    end
    
    g_tx_base = odssTransmitPulse(t, q, W, T, pulseType);
    g_rx_fun = @(u) odssTransmitPulse(u, q, W, T, pulseType);
    
    A_origin_raw = delay_scale_ambiguity( ...
        g_tx_base, t, g_rx_fun, 0, 1);
    
    if abs(A_origin_raw) < 1e-12
        error('A_{g_rx,g_tx}(0,1) is too small for normalization.');
    end
    
    H_diagonal = complex(zeros(M_tot,1));
    for idx = 1:M_tot
        n = pair_n(idx);
        m = pair_m(idx);
        H_nm = 0;
    
        for p = 1:Path_num
            tauAmbiguity = q^n * ( ...
                (m/W)*(alpha_path(p)-1) - ...
                alpha_path(p)*tau_path(p));
            scaleAmbiguity = 1/alpha_path(p);
    
            A_grx_gtx_raw = delay_scale_ambiguity( ...
                g_tx_base, t, g_rx_fun, ...
                tauAmbiguity, scaleAmbiguity);
            A_grx_gtx = A_grx_gtx_raw/A_origin_raw;
            H_nm = H_nm + h_path(p)*A_grx_gtx;
        end
    
        H_diagonal(idx) = H_nm;
    end
    
    H = diag(H_diagonal);
    D = diag(diag(H));
    
    %% 13.5 - 13.8 One-tap MMSE equalization
    Es_delayScale = mean(abs(X_vector).^2);
    sigmaW2_delayScale = mean(abs(W_vector).^2);
    mmseLoading = sigmaW2_delayScale/Es_delayScale;
    
    Zhat_vector = D' * ((D*D' + mmseLoading*eye(M_tot))\Yhat_vector);
    
    d = diag(D);
    Zhat_vector_scalar = conj(d) ./ (abs(d).^2+mmseLoading) .* Yhat_vector;
    
    
    %% 14. Inverse ODSS transform and QAM demodulation, Eq. (70)
    x_soft = T_iMF\Zhat_vector;
    rx_bits = qamdemod(x_soft, QAM_order, ...
        'OutputType', 'bit', 'UnitAveragePower', true);
    
    numBitErrors = nnz(rx_bits ~= tx_bits);
    BER = numBitErrors/numel(tx_bits);
    
    x_hat = qammod(rx_bits, QAM_order, ...
        'InputType', 'bit', 'UnitAveragePower', true);
    numSymbolErrors = nnz(x_hat ~= x_vector);
    SER = numSymbolErrors/M_tot;
    
    EbN0dB = SNRdB-10*log10(bitsPerSymbol);
    EbN0_linear = 10^(EbN0dB/10);
    BER_theory = qfunc(sqrt(2*EbN0_linear));
    

end
%% 10. Monte Carlo BER-SNR curve
% SNR is defined in the same way as the single-run simulation above:
% received waveform signal power divided by time-domain noise power.
%
% Instead of generating a long time-domain noise vector for every frame,
% generate its matched-filter output directly. Its covariance is exactly
%
%   E[W*W^H] = noisePower * Ts^2 * (G_rx^H*G_rx).
%
% This produces the same sampled AWGN statistics with much less runtime.
numCurveBits = numCurveFrames*numel(tx_bits);

noiseCovUnit = Ts^2*(G_rx'*G_rx);
noiseCovUnit = (noiseCovUnit+noiseCovUnit')/2;

[noiseCovSqrt, cholFlag] = chol(noiseCovUnit, 'lower');
if cholFlag ~= 0
    % Numerical fallback for a nearly positive-semidefinite covariance.
    [covVectors, covValues] = eig(noiseCovUnit);
    covEigenvalues = max(real(diag(covValues)), 0);
    noiseCovSqrt = covVectors*diag(sqrt(covEigenvalues));
end

BER_curve = zeros(size(SNRdB_curve));
numBitErrors_curve = zeros(size(SNRdB_curve));
BER_theory_curve = zeros(size(SNRdB_curve));

fprintf('BER-SNR Monte Carlo simulation\n');
fprintf('frames per SNR = %d, bits per SNR = %d\n', ...
    numCurveFrames, numCurveBits);

for snrIdx = 1:numel(SNRdB_curve)
    currentSNRdB = SNRdB_curve(snrIdx);
    currentNoisePower = signalPower/10^(currentSNRdB/10);

    unitNoise = (randn(M_tot,numCurveFrames) + ...
        1j*randn(M_tot,numCurveFrames))/sqrt(2);
    W_curve = sqrt(currentNoisePower)*noiseCovSqrt*unitNoise;
    Yhat_curve = bsxfun(@plus, W_curve, h0*X_vector);

    sigmaW2_curve = currentNoisePower * ...
        real(trace(noiseCovUnit))/M_tot;
    mmseLoading_curve = sigmaW2_curve/Es_delayScale;
    equalizerCurve = conj(d)./(abs(d).^2+mmseLoading_curve);
    Zhat_curve = bsxfun(@times, equalizerCurve, Yhat_curve);
    x_soft_curve = T_iMF\Zhat_curve;

    rxBitsCurve = qamdemod(x_soft_curve(:), ...
        QAM_order, 'OutputType', 'bit', ...
        'UnitAveragePower', true);
    repeatedTxBits = repmat(tx_bits, numCurveFrames, 1);
    bitErrorsAtCurrentSNR = nnz(rxBitsCurve ~= repeatedTxBits);

    numBitErrors_curve(snrIdx) = bitErrorsAtCurrentSNR;
    BER_curve(snrIdx) = bitErrorsAtCurrentSNR/numCurveBits;

    currentEbN0dB = currentSNRdB-10*log10(bitsPerSymbol);
    BER_theory_curve(snrIdx) = ...
        qfunc(sqrt(2*10^(currentEbN0dB/10)));

    fprintf('SNR = %5.1f dB: errors = %7d, BER = %.6e\n', ...
        currentSNRdB, bitErrorsAtCurrentSNR, ...
        BER_curve(snrIdx));
end

% A zero-error point is displayed at the conventional half-count upper
% bound so it remains visible on a logarithmic axis. BER_curve itself is
% saved without modification.
BER_curve_plot = BER_curve;
zeroErrorMask = (numBitErrors_curve == 0);
BER_curve_plot(zeroErrorMask) = 0.5/numCurveBits;

figure;
semilogy(SNRdB_curve, BER_curve_plot, 'o-', ...
    'LineWidth', 1.5, 'MarkerSize', 6);
hold on;
semilogy(SNRdB_curve, BER_theory_curve, '--', ...
    'LineWidth', 1.5);
grid on;
xlabel('SNR = E_s/N_0 (dB)');
ylabel('Bit Error Rate');
ylim([1e-6 1]);
title(sprintf('ODSS BER-SNR (%d frames per SNR)', ...
    numCurveFrames));
legend('ODSS simulation', 'Gray-coded QPSK theory', ...
    'Location', 'southwest');

berCurveFigureFile = fullfile(rxScriptDir, 'BER_SNR_curve.png');
saveas(gcf, berCurveFigureFile);

berCurveDataFile = fullfile(rxScriptDir, 'BER_SNR_data.mat');
save(berCurveDataFile, ...
    'SNRdB_curve', 'BER_curve', 'BER_curve_plot', ...
    'BER_theory_curve', 'numBitErrors_curve', ...
    'numCurveFrames', 'numCurveBits', 'zeroErrorMask');

fprintf('BER-SNR data saved successfully:\n%s\n', ...
    berCurveDataFile);
fprintf('BER-SNR figure saved successfully:\n%s\n\n', ...
    berCurveFigureFile);

%% 11. Save decoded data and receiver diagnostics
rxFormatVersion = 1;
save(rxDataFile, ...
    'rxFormatVersion', 'txDataFile', ...
    'SNRdB', 'h0', 'signalPower', 'noisePower', ...
    'measuredSNRdB', 'r', ...
    'Yhat_vector', 'Zhat_vector', ...
    'x_soft', 'rx_bits', 'x_hat', ...
    'numBitErrors', 'BER', ...
    'numSymbolErrors', 'SER', ...
    'EbN0dB', 'BER_theory', ...
    'H_diagonal', 'mmseLoading', ...
    'biorthErr', 'matchedFilterImplementationError', ...
    'noiseFilterImplementationError', 'linearityErr', ...
    'eq65ConstantChannelError', 'diagonalModelError', ...
    'mmseImplementationError', ...
    'SNRdB_curve', 'BER_curve', 'BER_theory_curve', ...
    'numBitErrors_curve', 'numCurveFrames', 'numCurveBits');

fprintf('Decoded receiver data saved successfully:\n%s\n', rxDataFile);

%% 12. Constellation
figure;
plot(real(x_soft), imag(x_soft), 'o');
hold on;
plot(real(x_vector), imag(x_vector), 'kx', 'LineWidth', 1.5);
grid on;
axis equal;
xlabel('In-phase');
ylabel('Quadrature');
title(sprintf('ODSS over pure AWGN, SNR = %.1f dB', SNRdB));
legend('Before slicing', 'Transmitted 4-QAM', 'Location', 'best');


%% supported functions
function A = matchedFilterSample(r, t, template)

r = r(:);
t = t(:);
template = template(:);

if numel(r) ~= numel(t)
    error('r and t must have the same number of samples.');
end

if numel(template) ~= numel(r)
    error('template and r must have the same number of samples.');
end

if numel(t) < 2
    error('The time vector must contain at least two samples.');
end

TsLocal = t(2)-t(1);
A = TsLocal*(template'*r);

end

function A = delay_scale_ambiguity(r, t, g_rx_fun, tau, alpha)

r = r(:);
t = t(:);

if numel(r) ~= numel(t)
    error('r and t must have the same number of samples.');
end

if numel(t) < 2
    error('t must contain at least two samples.');
end

if alpha <= 0
    error('alpha must be positive.');
end

template = sqrt(alpha).*g_rx_fun(alpha.*(t-tau));
template = template(:);
A = matchedFilterSample(r, t, template);

end
